name: terraform_destroy
on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to destroy'
          required: true
jobs:
  destroy:
    environment:
      name: ${{ github.event.inputs.environment }} 
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
      
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.11"
            terraform_wrapper: false
        - name: az login
          uses: azure/login@v3
          with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: terraform destroy
          run: |
            echo "Destroying environment: ${{ github.event.inputs.environment }}"
            cd infra/envs/${{ github.event.inputs.environment }}
            terraform init
            terraform destroy -var="tenant_id=${{ vars.tenant_id }}" -auto-approve
            echo "Environment ${{ github.event.inputs.environment }} destroyed successfully."