name: platform_deployment
on:
    pull_request:
      branches:
        - main
    workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to deploy to'
          required: true
        tenant_id:
          description: 'Tenant ID for the deployment'
          required: true
jobs:
  deploy:
    environment:
      name: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
      
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.11"
            terraform_wrapper: false
        - name: az login
          uses: azure/login@v3
          with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: terraform init 
          run: | 

            cd infra/envs/${{ github.event.inputs.environment }}
            terraform init
          
        - name: terraform plan
          run: |
            cd infra/envs/${{ github.event.inputs.environment }}
            terraform plan -var="tenant_id=${{ github.event.inputs.tenant_id }}"
        
        - name: terraform apply
          run: |
            cd infra/envs/${{ github.event.inputs.environment }}
            terraform apply -auto-approve -var="tenant_id=${{ github.event.inputs.tenant_id }}"