name: platform_deployment
on:
    pull_request:
      branches:
        - main
    workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to deploy to'
          required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
      
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.9.8"
            terraform_wrapper: false

        - name: terraform init 
          run: | 

            cd infra/envs/${{ github.event.inputs.environment }}
            terraform init
